## Initial Exploratory Data Analysis

In [101]:
import numpy as np
import pandas as pd

results = pd.read_csv("../data/01_raw/results.csv")
races = pd.read_csv("../data/01_raw/races.csv")
drivers = pd.read_csv("../data/01_raw/drivers.csv")
constructors = pd.read_csv("../data/01_raw/constructors.csv")
status = pd.read_csv("../data/01_raw/status.csv")

In [7]:
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [11]:
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [12]:
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [13]:
constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [25]:
status

     statusId          status
0           1        Finished
1           2    Disqualified
2           3        Accident
3           4       Collision
4           5          Engine
..        ...             ...
134       137          Damage
135       138          Debris
136       139         Illness
137       140       Undertray
138       141  Cooling system

[139 rows x 2 columns]

In [63]:
# Verifying outliers
results_status = pd.merge(left=status, right=results, left_on="statusId", right_on="statusId", how="inner",
                          validate="one_to_many")
results_status[["statusId", "status", "number"]].groupby(by=["statusId", "status"]).count()

                         number
statusId status
1        Finished          7674
2        Disqualified       147
3        Accident          1062
4        Collision          854
5        Engine            2026
...                         ...
137      Damage               2
138      Debris               1
139      Illness              3
140      Undertray            4
141      Cooling system       1

[137 rows x 1 columns]

In [138]:
# Verifying statuses who disqualify
results_status['is_dnf'] = np.where(results_status['position'] == '\\N', 'DNF (\\N)', 'Finished')

is_dnf_count = results_status.groupby(['statusId', 'status', 'is_dnf']).size().reset_index(name='total_occurrences')

view_dnf_count_table = is_dnf_count.pivot_table(
    index=['statusId', 'status'],
    columns='is_dnf',
    values='total_occurrences',
    fill_value=0
)

view_dnf_count_table

is_dnf                   DNF (\N)  Finished
statusId status
1        Finished             0.0    7674.0
2        Disqualified       147.0       0.0
3        Accident           987.0      75.0
4        Collision          806.0      48.0
5        Engine            1886.0     140.0
...                           ...       ...
137      Damage               2.0       0.0
138      Debris               1.0       0.0
139      Illness              3.0       0.0
140      Undertray            4.0       0.0
141      Cooling system       1.0       0.0

[137 rows x 2 columns]

### Creating Sub-Groups by status

In [139]:
status_group = {
    1: "Finished", 2: "Disqualified", 3: "Incident", 4: "Incident", 5: "Mechanical", 6: "Mechanical", 7: "Mechanical",
    8: "Mechanical", 9: "Mechanical", 10: "Mechanical", 11: "Finished", 12: "Finished", 13: "Finished", 14: "Finished",
    15: "Finished", 16: "Finished", 17: "Finished", 18: "Finished", 19: "Finished", 20: "Incident", 21: "Mechanical",
    22: "Mechanical", 23: "Mechanical", 24: "Mechanical", 25: "Mechanical", 26: "Mechanical", 27: "Mechanical",
    28: "Mechanical", 29: "Mechanical", 30: "Mechanical", 31: "Mechanical", 32: "Mechanical", 33: "Mechanical",
    34: "Mechanical", 35: "Disqualified", 36: "Mechanical", 37: "Mechanical", 38: "Mechanical", 39: "Mechanical",
    40: "Mechanical", 41: "Mechanical", 42: "Mechanical", 43: "Mechanical", 44: "Mechanical", 45: "Finished",
    46: "Finished",
    47: "Mechanical", 48: "Mechanical", 49: "Mechanical", 50: "Finished", 51: "Mechanical", 53: "Finished",
    54: "Disqualified",
    55: "Finished", 56: "Mechanical", 58: "Disqualified", 59: "Finished", 60: "Finished", 61: "Mechanical",
    62: "Disqualified",
    63: "Mechanical", 64: "Mechanical", 65: "Mechanical", 66: "Mechanical", 67: "Mechanical", 68: "Incident",
    69: "Mechanical",
    70: "Mechanical", 71: "Mechanical", 72: "Mechanical", 73: "Incident", 74: "Mechanical", 75: "Mechanical",
    76: "Mechanical", 77: "Disqualified", 78: "Disqualified", 79: "Mechanical", 80: "Mechanical", 81: "Disqualified",
    82: "Incident", 83: "Mechanical", 84: "Mechanical", 85: "Mechanical", 86: "Mechanical", 87: "Mechanical",
    88: "Finished", 89: "Disqualified", 90: "Disqualified", 91: "Mechanical", 92: "Mechanical", 93: "Disqualified",
    94: "Mechanical", 95: "Mechanical", 96: "Disqualified", 97: "Disqualified", 98: "Mechanical", 99: "Mechanical",
    100: "Disqualified", 101: "Disqualified", 102: "Mechanical", 103: "Mechanical", 104: "Disqualified", 105: "Mechanical",
    106: "Mechanical", 107: "Disqualified", 108: "Mechanical", 109: "Mechanical", 110: "Mechanical", 111: "Finished",
    112: "Finished", 113: "Finished", 114: "Finished", 115: "Finished", 116: "Finished", 117: "Finished",
    118: "Finished", 119: "Finished", 120: "Finished", 121: "Mechanical", 122: "Finished", 123: "Finished",
    124: "Finished", 125: "Finished", 126: "Mechanical", 127: "Finished", 128: "Disqualified", 129: "Disqualified",
    130: "Disqualified", 131: "Mechanical", 132: "Mechanical", 135: "Mechanical", 136: "Mechanical",
    137: "Incident", 138: "Disqualified", 139: "Disqualified", 140: "Mechanical", 141: "Mechanical",
}

status['status_group'] = status['statusId'].map(status_group)
status = status.dropna(subset=['status_group'])

status

     statusId          status  status_group
0           1        Finished      Finished
1           2    Disqualified  Disqualified
2           3        Accident      Incident
3           4       Collision      Incident
4           5          Engine    Mechanical
..        ...             ...           ...
134       137          Damage      Incident
135       138          Debris  Disqualified
136       139         Illness  Disqualified
137       140       Undertray    Mechanical
138       141  Cooling system    Mechanical

[137 rows x 3 columns]

 ## Joining Data

In [140]:
results_races = pd.merge(left=races, right=results, left_on="raceId", right_on="raceId", how="inner",
                         validate="one_to_many")
results_races_drivers = pd.merge(left=drivers, right=results_races, left_on="driverId", right_on="driverId",
                                 how="inner", validate="one_to_many")
results_races_drivers_constructors = pd.merge(left=constructors, right=results_races_drivers, left_on="constructorId",
                                              right_on="constructorId", how="inner", validate="one_to_many")
data_post_merge = pd.merge(left=status, right=results_races_drivers_constructors, left_on="statusId",
                           right_on="statusId", how="inner", validate="one_to_many")

data_post_merge.to_csv("../data/02_interim/results_races_drivers_constructors.csv", index=False)