### Data Leakage Elimination

In [26]:
import pandas as pd

df = pd.read_csv('../train_data/02_interim/01_raw_gp_summary.csv')

df

,statusId,status,qualifyId,raceId,driverId,constructorId_qualifying,number_qualifying,position_qualifying,q1,q2,...,positionText,positionOrder,points,laps,time_result,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed
0,1,Finished,1,18,1,1,22,1,1:26.572,1:25.187,...,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300
1,1,Finished,3,18,5,1,23,3,1:25.664,1:25.452,...,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385
2,1,Finished,5,18,2,2,3,5,1:25.960,1:25.518,...,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586
3,1,Finished,7,18,3,3,7,7,1:26.295,1:26.059,...,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719
4,1,Finished,12,18,4,4,5,12,1:26.907,1:26.188,...,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,140,Undertray,9411,1084,849,3,6,19,1:07.003,\N,...,R,19,0.0,48,\N,\N,14,19,1:10.890,219.280
10490,140,Undertray,9420,1085,852,213,22,8,1:33.394,1:32.836,...,R,20,0.0,17,\N,\N,4,20,1:40.216,209.858
10491,140,Undertray,9881,1111,844,6,16,9,1:22.019,1:19.600,...,R,19,0.0,41,\N,\N,33,19,1:17.277,198.408
10492,140,Undertray,9989,1116,4,117,14,17,1:36.268,\N,...,R,16,0.0,49,\N,\N,47,7,1:39.954,198.559
10493,141,Cooling system,9220,1075,822,51,77,8,1:29.683,1:29.404,...,R,15,0.0,36,\N,\N,31,14,1:33.979,236.503

In [27]:
df = df.drop(['position', 'positionText', 'points', 'time_result', 'milliseconds', 'fastestLap',
               'rank', 'fastestLapTime', 'fastestLapSpeed'], axis=1)
df

,statusId,status,qualifyId,raceId,driverId,constructorId_qualifying,number_qualifying,position_qualifying,q1,q2,...,fp3_time,quali_date,quali_time,sprint_date,sprint_time,resultId,number,grid,positionOrder,laps
0,1,Finished,1,18,1,1,22,1,1:26.572,1:25.187,...,\N,\N,\N,\N,\N,1,22,1,1,58
1,1,Finished,3,18,5,1,23,3,1:25.664,1:25.452,...,\N,\N,\N,\N,\N,5,23,3,5,58
2,1,Finished,5,18,2,2,3,5,1:25.960,1:25.518,...,\N,\N,\N,\N,\N,2,3,5,2,58
3,1,Finished,7,18,3,3,7,7,1:26.295,1:26.059,...,\N,\N,\N,\N,\N,3,7,7,3,58
4,1,Finished,12,18,4,4,5,12,1:26.907,1:26.188,...,\N,\N,\N,\N,\N,4,5,11,4,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,140,Undertray,9411,1084,849,3,6,19,1:07.003,\N,...,\N,2022-07-08,15:00:00,2022-07-09,14:30:00,25624,6,17,19,48
10490,140,Undertray,9420,1085,852,213,22,8,1:33.394,1:32.836,...,11:00:00,2022-07-23,14:00:00,\N,\N,25645,22,8,20,17
10491,140,Undertray,9881,1111,844,6,16,9,1:22.019,1:19.600,...,09:30:00,2023-08-26,13:00:00,\N,\N,26104,16,9,19,41
10492,140,Undertray,9989,1116,4,117,14,17,1:36.268,\N,...,\N,2023-10-20,21:00:00,2023-10-21,22:00:00,26201,14,0,16,49
10493,141,Cooling system,9220,1075,822,51,77,8,1:29.683,1:29.404,...,14:00:00,2022-03-26,17:00:00,\N,\N,25440,77,8,15,36

In [28]:
df.to_csv('../data/02_interim/02_dataset_without_leakage.csv', index=False)